import React, { useEffect, useMemo, useState, useRef } from 'react'
import { ChefHat, ClipboardList, Coffee, CreditCard, LayoutGrid, LogOut, Menu as MenuIcon, Plus, Settings2, ShoppingBag, Sun, Trash2, Users, Utensils, X, Check, ArrowRight } from 'lucide-react'
import { Canvas, useFrame } from '@react-three/fiber'

const roles = { gerant:'Gérant', serveur:'Serveur', cuisinier:'Cuisinier', caissier:'Caissier' }
const initialDishes = [
  {id:1, category:'Entrées', name:'Œuf parfait, champignons', desc:'Crème de sous-bois, huile de persil', price:12, available:true},
  {id:2, category:'Entrées', name:'Poireau vinaigrette', desc:'Noisettes torréfiées, œuf mimosa', price:9, available:true},
  {id:3, category:'Plats', name:'Volaille rôtie', desc:'Jus corsé, pommes grenailles, ail noir', price:24, available:true},
  {id:4, category:'Plats', name:'Pêche du jour', desc:'Beurre blanc, fenouil braisé', price:27, available:true},
  {id:5, category:'Desserts', name:'Tarte fine aux pommes', desc:'Crème crue vanillée', price:10, available:true},
  {id:6, category:'Boissons', name:'Jus de pomme artisanal', desc:'Verger de Normandie — 25cl', price:5, available:false}
]
const seedOrders = [{id:'CMD-104', table:4, status:'cooking', items:[{name:'Volaille rôtie', qty:2, price:24},{name:'Tarte fine aux pommes', qty:1, price:10}], total:58}]
const money = n => new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n)

function RotatingTorus(){
  const ref = useRef()
  useFrame((_, delta) => { if(ref.current){ ref.current.rotation.x += delta; ref.current.rotation.y += delta * 0.7 } })
  return (
    <mesh ref={ref} scale={[0.9,0.9,0.9]}>
      <torusGeometry args={[0.8,0.28,16,64]} />
      <meshStandardMaterial color="#151412" metalness={0.6} roughness={0.25} />
    </mesh>
  )
}

function App(){
  const [user,setUser] = useState(()=>JSON.parse(localStorage.getItem('lc-user')||'null'))
  const [screen,setScreen] = useState('salle')
  const [theme,setTheme] = useState(()=>localStorage.getItem('lc-theme')||'dark')
  const [dishes,setDishes] = useState(()=>JSON.parse(localStorage.getItem('lc-dishes')||JSON.stringify(initialDishes)))
  const [orders,setOrders] = useState(()=>JSON.parse(localStorage.getItem('lc-orders')||JSON.stringify(seedOrders)))
  const [tables,setTables] = useState(()=>JSON.parse(localStorage.getItem('lc-tables')||JSON.stringify(Array.from({length:12},(_,i)=>({id:i+1,status:i===3?'occupied':'free'})))))
  const [activeTable,setActiveTable] = useState(null)
  const [cart,setCart] = useState([])
  useEffect(()=>localStorage.setItem('lc-dishes',JSON.stringify(dishes)),[dishes]); useEffect(()=>localStorage.setItem('lc-orders',JSON.stringify(orders)),[orders]); useEffect(()=>localStorage.setItem('lc-tables',JSON.stringify(tables)),[tables]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('lc-theme',theme)},[theme])
  if(!user) return <Login onLogin={u=>{setUser(u);localStorage.setItem('lc-user',JSON.stringify(u))}} />
  const can = p => user.role==='gerant' || p.includes(user.role)
  const nav = [{id:'salle',label:'Salle & commandes',icon:LayoutGrid,roles:['gerant','serveur']},{id:'cuisine',label:'Cuisine',icon:ChefHat,roles:['gerant','cuisinier']},{id:'caisse',label:'Caisse',icon:CreditCard,roles:['gerant','caissier']},{id:'menu',label:'Menu',icon:Utensils,roles:['gerant']}].filter(x=>can(x.roles))
  const select = id => {setScreen(id);setActiveTable(null);setCart([])}
  return <div className="noise min-h-screen bg-[#151412] text-[#f6f0e7]">
    <aside className="fixed inset-y-0 z-20 hidden w-64 border-r border-white/10 bg-[#1b1916] p-5 lg:block"><Brand/><div className="mt-12 space-y-1">{nav.map(n=><NavItem key={n.id} {...n} active={screen===n.id} onClick={()=>select(n.id)}/>)}</div><div className="absolute bottom-5 left-5 right-5"><div className="mb-4 rounded-xl bg-[#25221e] p-3"><p className="text-xs muted">SESSION ACTIVE</p><p className="mt-1 font-semibold">{user.name}</p><p className="text-xs text-[#dc6b42]">{roles[user.role]}</p></div><button className="btn-ghost w-full" onClick={()=>{setUser(null);localStorage.removeItem('lc-user')}}><LogOut size={16}/>Se déconnecter</button></div></aside>
    <main className="lg:ml-64"><header className="flex items-center justify-between border-b border-white/10 px-5 py-4 md:px-10"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#dc6b42]">leComptoir / {screen}</p><h1 className="mt-1 font-display text-2xl capitalize">{screen==='salle'?'Service du soir':screen}</h1></div><div className="flex items-center gap-2"><button className="btn-ghost !p-2.5" onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Sun size={17}/></button><div className="hidden text-right sm:block"><p className="text-sm font-semibold">{user.name}</p><p className="text-xs muted">{roles[user.role]}</p></div></div></header><div className="border-b border-white/10 bg-[#1b1916] px-5 py-2 lg:hidden"><div className="flex gap-2 overflow-x-auto">{nav.map(n=><button key={n.id} onClick={()=>select(n.id)} className={`btn whitespace-nowrap !px-3 !py-2 ${screen===n.id?'bg-[#dc6b42]':'bg-white/5'}`}><n.icon size={15}/>{n.label}</button>)}</div></div><div className="p-5 md:p-10">{screen==='salle'&&<Floor tables={tables} active={activeTable} onSelect={t=>{setActiveTable(t);setCart([])}}/>}{screen==='menu'&&<Menu dishes={dishes} setDishes={setDishes}/>} {screen==='cuisine'&&<Kitchen orders={orders} setOrders={setOrders}/>} {screen==='caisse'&&<Cash orders={orders} setOrders={setOrders} tables={tables} setTables={setTables}/>}</div></main>
    {activeTable&&<OrderPanel table={activeTable} dishes={dishes} cart={cart} setCart={setCart} onClose={()=>setActiveTable(null)} onSend={()=>{if(!cart.length)return;const total=cart.reduce((a,x)=>a+x.price*x.qty,0);setOrders(o=>[...o,{id:'CMD-'+(105+o.length),table:activeTable,items:cart,status:'cooking',total}]);setTables(ts=>ts.map(t=>t.id===activeTable?{...t,status:'occupied'}:t));setCart([]);setActiveTable(null)}}/>}
  </div>
}
function Brand(){return <div className="flex items-center gap-3"><div className="relative rounded-xl bg-[#dc6b42] p-2" style={{width:48,height:48}}><Coffee size={20}/><div className="hidden sm:block" style={{position:'absolute',right:-8,bottom:-8,width:48,height:48}}><Canvas style={{width:'48px',height:'48px'}} camera={{position:[0,0,5], fov:50}}>
  <ambientLight intensity={0.6}/>
  <directionalLight position={[2,2,2]} intensity={0.8}/>
  <RotatingTorus />
</Canvas></div></div><div><p className="font-display text-xl">leComptoir</p><p className="text-[10px] uppercase tracking-[.2em] muted">restaurant ops</p></div></div>}
function NavItem({icon:Icon,label,active,onClick}){return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold transition ${active?'bg-[#dc6b42] text-white':'muted hover:bg-white/5 hover:text-white'}`}><Icon size={18}/>{label}</button>}
function Login({onLogin}){const [role,setRole]=useState('gerant');return <div className="flex min-h-screen items-center justify-center bg-[#151412] p-5"><div className="w-full max-w-md"><Brand/><div className="card mt-10 p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#dc6b42]">Espace équipe</p><h1 className="mt-3 font-display text-3xl">Bon service.</h1><p className="mt-2 text-sm muted">Connectez-vous pour accéder à votre poste.</p><label className="mt-7 block text-sm font-semibold">Adresse email<input className="field mt-2" placeholder="prenom@lecomptoir.fr" /></label><label className="mt-4 block text-sm font-semibold">Mot de passe<input className="field mt-2" type="password" placeholder="••••••••" /></label><p className="mt-5 text-xs muted">Prototype local : choisissez un rôle pour explorer les permissions.</p><div className="mt-2 grid grid-cols-2 gap-2">{Object.entries(roles).map(([k,v])=><button key={k} onClick={()=>setRole(k)} className={`rounded-xl border p-3 text-left text-sm ${role===k?'border-[#dc6b42] bg-[#dc6b42]/15 text-white':'border-white/10 muted'}`}><Users size={15} className="mb-2"/>{v}</button>)}</div><button className="btn-primary mt-6 w-full" onClick={()=>onLogin({name:roles[role],role})}>Entrer dans le comptoir <ArrowRight size={16}/></button></div></div></div>}
function Floor({tables,active,onSelect}){return <section><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm muted">Vue opérationnelle</p><h2 className="mt-1 font-display text-4xl">La salle</h2></div><div className="flex gap-4 text-xs muted"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#8cba8b]"/>Libre</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#dc6b42]"/>Occupée</span></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-6">{tables.map(t=><button key={t.id} onClick={()=>onSelect(t.id)} className={`card flex aspect-square flex-col items-center justify-center transition hover:-translate-y-1 ${active===t.id?'ring-2 ring-[#dc6b42]':''}`}><span className={`mb-3 grid h-12 w-12 place-items-center rounded-full ${t.status==='free'?'bg-[#8cba8b]/15 text-[#8cba8b]':'bg-[#dc6b42]/15 text-[#dc6b42]'}`}><span className="text-lg font-bold">{t.id}</span></span><span className="text-sm font-semibold">Table {t.id}</span><span className="mt-1 text-xs muted">{t.status==='free'?'Disponible':'En service'}</span></button>)}</div></section>}
function OrderPanel({table,dishes,cart,setCart,onClose,onSend}){const [cat,setCat]=useState('Toutes');const cats=['Toutes',...new Set(dishes.map(d=>d.category))];const shown=dishes.filter(d=>(cat==='Toutes'||d.category===cat)&&d.available);const add=d=>setCart(c=>c.some(x=>x.id===d.id)?c.map(x=>x.id===d.id?{...x,qty:x.qty+1}:x):[...c,{...d,qty:1}]);const total=cart.reduce((a,x)=>a+x.price*x.qty,0);return <div className="fixed inset-0 z-30 flex justify-end bg-black/60" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="flex h-full w-full max-w-2xl flex-col bg-[#1b1916] shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-xs uppercase tracking-widest text-[#dc6b42]">Nouvelle commande</p><h2 className="font-display text-2xl">Table {table}</h2></div><button className="btn-ghost !p-2" onClick={onClose}><X size={18}/></button></div><div className="flex gap-2 overflow-x-auto border-b border-white/10 p-4">{cats.map(c=><button onClick={()=>setCat(c)} className={`btn whitespace-nowrap !px-3 !py-2 ${cat===c?'bg-[#dc6b42]':'bg-white/5'}`} key={c}>{c}</button>)}</div><div className="grid flex-1 content-start grid-cols-1 gap-3 overflow-y-auto p-5 sm:grid-cols-2">{shown.map(d=><button key={d.id} onClick={()=>add(d)} className="card p-4 text-left hover:border-[#dc6b42]"><div className="flex justify-between gap-3"><b>{d.name}</b><span className="text-[#dc6b42]">{money(d.price)}</span></div><p className="mt-1 text-xs muted">{d.desc}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#dc6b42]"><Plus size={13}/>Ajouter</span></button>)}</div><div className="border-t border-white/10 bg-[#211f1b] p-5"><p className="mb-3 text-xs font-bold uppercase tracking-widest muted">Panier · {cart.reduce((a,x)=>a+x.qty,0)} article(s)</p>{cart.length===0?<p className="text-sm muted">Sélectionnez des plats pour commencer.</p>:<div className="mb-4 space-y-2">{cart.map(x=><div className="flex justify-between text-sm" key={x.id}><span>{x.qty} × {x.name}</span><span>{money(x.qty*x.price)}</span></div>)}</div>}<div className="mb-4 flex justify-between border-t border-white/10 pt-3 font-display text-xl"><span>Total</span><span>{money(total)}</span></div><button disabled={!cart.length} className="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-40" onClick={onSend}>Envoyer en cuisine <ArrowRight size={16}/></button></div></div></div>}
function Kitchen({orders,setOrders}){const active=orders.filter(o=>o.status==='cooking');return <section><p className="text-sm muted">Flux en temps réel</p><h2 className="mt-1 font-display text-4xl">À préparer</h2><div className="mt-8 grid gap-4 lg:grid-cols-2">{active.length?active.map(o=><div className="card p-5" key={o.id}><div className="flex justify-between"><div><span className="rounded-full bg-[#dc6b42]/15 px-2 py-1 text-xs font-bold text-[#ed8b68]">{o.id}</span><h3 className="mt-3 text-xl font-semibold">Table {o.table}</h3></div><ChefHat className="text-[#dc6b42]"/></div><div className="my-5 space-y-2 border-y border-white/10 py-4">{o.items.map((x,i)=><div className="flex justify-between text-sm" key={i}><span><b>{x.qty}×</b> {x.name}</span><span className="muted">{money(x.qty*x.price)}</span></div>)}</div><button className="btn-primary w-full" onClick={()=>setOrders(os=>os.map(x=>x.id===o.id?{...x,status:'ready'}:x))}><Check size={16}/>Marquer prête</button></div>):<Empty icon={ChefHat} text="La cuisine est à jour"/>}</div></section>}
function Cash({orders,setOrders,tables,setTables}){const ready=orders.filter(o=>o.status==='ready');return <section><p className="text-sm muted">Dernière étape du service</p><h2 className="mt-1 font-display text-4xl">À encaisser</h2><div className="mt-8 grid gap-4 lg:grid-cols-2">{ready.length?ready.map(o=><div className="card p-5" key={o.id}><div className="flex justify-between"><div><span className="rounded-full bg-[#8cba8b]/15 px-2 py-1 text-xs font-bold text-[#8cba8b]">PRÊTE</span><h3 className="mt-3 text-xl font-semibold">Table {o.table} <span className="text-sm font-normal muted">· {o.id}</span></h3></div><CreditCard className="text-[#8cba8b]"/></div><div className="my-5 space-y-2 border-y border-white/10 py-4">{o.items.map((x,i)=><div className="flex justify-between text-sm" key={i}><span>{x.qty}× {x.name}</span><span>{money(x.qty*x.price)}</span></div>)}</div><div className="mb-4 flex justify-between font-display text-2xl"><span>Total</span><span>{money(o.total)}</span></div><button className="btn-primary w-full bg-[#8cba8b] text-[#151412] hover:bg-[#a7d3a5]" onClick={()=>{setOrders(os=>os.map(x=>x.id===o.id?{...x,status:'paid'}:x));setTables(ts=>ts.map(t=>t.id===o.table?{...t,status:'free'}:t))}}><Check size={16}/>Valider le paiement</button></div>):<Empty icon={CreditCard} text="Aucun paiement en attente"/>}</div></section>}
function Menu({dishes,setDishes}){const [editing,setEditing]=useState(null);const [cat,setCat]=useState('Toutes');const cats=['Toutes',...new Set(dishes.map(d=>d.category))];const shown=dishes.filter(d=>cat==='Toutes'||d.category===cat);const save=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const item={id:editing?.id||Date.now(),name:f.get('name'),desc:f.get('desc'),category:f.get('category'),price:Number(f.get('price')),available:f.get('available')==='on'};setDishes(ds=>editing?ds.map(d=>d.id===editing.id?item:d):[...ds,item]);setEditing(null)};return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm muted">Catalogue en service</p><h2 className="mt-1 font-display text-4xl">Le menu</h2></div><button className="btn-primary" onClick={()=>setEditing({})}><Plus size={17}/>Nouveau plat</button></div><div className="my-7 flex gap-2 overflow-x-auto">{cats.map(c=><button onClick={()=>setCat(c)} className={`btn whitespace-nowrap !px-3 !py-2 ${cat===c?'bg-[#dc6b42]':'bg-white/5'}`} key={c}>{c}</button>)}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{shown.map(d=><div className="card p-5" key={d.id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{d.name}</h3><p className="mt-1 text-sm muted">{d.desc}</p></div><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${d.available?'bg-[#8cba8b]':'bg-white/20'}`}/></div><div className="mt-6 flex items-center justify-between"><span className="font-display text-xl">{money(d.price)}</span><button className="btn-ghost !px-3 !py-2" onClick={()=>setEditing(d)}><Settings2 size={14}/>Modifier</button></div></div>)}</div>{editing&&<div className="fixed inset-0 z-30 grid place-items-center bg-black/70 p-5"><form onSubmit={save} className="card w-full max-w-md p-6"><div className="flex justify-between"><h3 className="font-display text-2xl">{editing.id?'Modifier le plat':'Nouveau plat'}</h3><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="mt-5 space-y-3"><input required name="name" defaultValue={editing.name} className="field" placeholder="Nom du plat"/><input required name="desc" defaultValue={editing.desc} className="field" placeholder="Description courte"/><div className="grid grid-cols-2 gap-3"><select name="category" defaultValue={editing.category||'Plats'} className="field"><option>Entrées</option><option>Plats</option><option>Desserts</option><option>Boissons</option></select><input required name="price" type="number" step=".5" defaultValue={editing.price} className="field" placeholder="Prix"/></div><label className="flex items-center gap-2 text-sm"><input name="available" type="checkbox" defaultChecked={editing.available!==false} className="accent-[#dc6b42]"/> Disponible à la commande</label></div><button className="btn-primary mt-6 w-full">Enregistrer</button></form></div>}</section>}
function Empty({icon:Icon,text}){return <div className="card col-span-full flex min-h-48 flex-col items-center justify-center text-center"><Icon size={30} className="mb-3 text-[#dc6b42]"/><p className="muted">{text}</p></div>}

export default App
